my:
	javac -cp ../hadoop-core-1.0.1.jar:../lib/commons-cli-1.2.jar -d mywordcount_classes MyWordCount.java 

ex:
	javac -cp ../hadoop-core-1.0.1.jar -d mywordcount_classes WordCount.java 
exjar:
	jar -cvf ./wordcount.jar -C mywordcount_classes/ .
